[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "loader"
path = "src/main.rs"

[dependencies]
log = "0.4.20"
uefi = { version = "0.30.0", features = [ "panic_handler", "logger", "alloc", "global_allocator" ] } # https://crates.io/crates/uefi